In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('My Males Covid Data.csv')

In [3]:
df

Unnamed: 0   DATE_DIED  INTUBED  PNEUMONIA  AGE  DIABETES  ASTHMA  \
0                1  03/06/2020       97          1   72         2       2   
1                2  09/06/2020        1          2   55         1       2   
2                4  21/06/2020       97          2   68         1       2   
3               11  9999-99-99        2          2   24         2       2   
4               12  9999-99-99        2          2   30         2       2   
...            ...         ...      ...        ...  ...       ...     ...   
523506     1048570  9999-99-99       97          2   40         2       2   
523507     1048571  9999-99-99        2          2   51         2       2   
523508     1048572  9999-99-99       97          2   55         2       2   
523509     1048573  9999-99-99       97          2   28         2       2   
523510     1048574  9999-99-99       97          2   52         2       2   

        OTHER_DISEASE  CARDIOVASCULAR  OBESITY  TOBACCO  ICU STATUS  \
0                   2               2        1        2   97   Died   
1                   2               2        2        2    2   Died   
2                   2               2        2        2   97   Died   
3                   2               2        2        2    2  Cured   
4                   2               2        2        2    2  Cured   
...               ...             ...      ...      ...  ...    ...   
523506              2               2        2        2   97  Cured   
523507              2               2        2        2    2  Cured   
523508              2               2        2        2   97  Cured   
523509              2               2        2        2   97  Cured   
523510              2               2        2        2   97  Cured   

          DAY_DIED MONTH_DIED  
0               03     ['06']  
1               09     ['06']  
2               21     ['06']  
3       9999-99-99         []  
4       9999-99-99         []  
...            ...        ...  
523506  9999-99-99         []  
523507  9999-99-99         []  
523508  9999-99-99         []  
523509  9999-99-99         []  
523510  9999-99-99         []  

[523511 rows x 15 columns]

In [4]:
df['STATUS'] = df['DATE_DIED'].apply(lambda x : 1 if '9999-99-99' in x else 0)
df

Unnamed: 0   DATE_DIED  INTUBED  PNEUMONIA  AGE  DIABETES  ASTHMA  \
0                1  03/06/2020       97          1   72         2       2   
1                2  09/06/2020        1          2   55         1       2   
2                4  21/06/2020       97          2   68         1       2   
3               11  9999-99-99        2          2   24         2       2   
4               12  9999-99-99        2          2   30         2       2   
...            ...         ...      ...        ...  ...       ...     ...   
523506     1048570  9999-99-99       97          2   40         2       2   
523507     1048571  9999-99-99        2          2   51         2       2   
523508     1048572  9999-99-99       97          2   55         2       2   
523509     1048573  9999-99-99       97          2   28         2       2   
523510     1048574  9999-99-99       97          2   52         2       2   

        OTHER_DISEASE  CARDIOVASCULAR  OBESITY  TOBACCO  ICU  STATUS  \
0                   2               2        1        2   97       0   
1                   2               2        2        2    2       0   
2                   2               2        2        2   97       0   
3                   2               2        2        2    2       1   
4                   2               2        2        2    2       1   
...               ...             ...      ...      ...  ...     ...   
523506              2               2        2        2   97       1   
523507              2               2        2        2    2       1   
523508              2               2        2        2   97       1   
523509              2               2        2        2   97       1   
523510              2               2        2        2   97       1   

          DAY_DIED MONTH_DIED  
0               03     ['06']  
1               09     ['06']  
2               21     ['06']  
3       9999-99-99         []  
4       9999-99-99         []  
...            ...        ...  
523506  9999-99-99         []  
523507  9999-99-99         []  
523508  9999-99-99         []  
523509  9999-99-99         []  
523510  9999-99-99         []  

[523511 rows x 15 columns]

In [5]:
df.columns

Index(['Unnamed: 0', 'DATE_DIED', 'INTUBED', 'PNEUMONIA', 'AGE', 'DIABETES',
       'ASTHMA', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY', 'TOBACCO',
       'ICU', 'STATUS', 'DAY_DIED', 'MONTH_DIED'],
      dtype='object')

In [6]:
df['DAY_DIED'] = df['DAY_DIED'].apply(lambda x : 1 if '9999-99-99' in x else x)

In [7]:
df.columns

Index(['Unnamed: 0', 'DATE_DIED', 'INTUBED', 'PNEUMONIA', 'AGE', 'DIABETES',
       'ASTHMA', 'OTHER_DISEASE', 'CARDIOVASCULAR', 'OBESITY', 'TOBACCO',
       'ICU', 'STATUS', 'DAY_DIED', 'MONTH_DIED'],
      dtype='object')

In [8]:
df_model =df[['AGE','INTUBED','DIABETES','ICU','CARDIOVASCULAR','ASTHMA','STATUS','PNEUMONIA','DAY_DIED']]
df_model

AGE  INTUBED  DIABETES  ICU  CARDIOVASCULAR  ASTHMA  STATUS  \
0        72       97         2   97               2       2       0   
1        55        1         1    2               2       2       0   
2        68       97         1   97               2       2       0   
3        24        2         2    2               2       2       1   
4        30        2         2    2               2       2       1   
...     ...      ...       ...  ...             ...     ...     ...   
523506   40       97         2   97               2       2       1   
523507   51        2         2    2               2       2       1   
523508   55       97         2   97               2       2       1   
523509   28       97         2   97               2       2       1   
523510   52       97         2   97               2       2       1   

        PNEUMONIA DAY_DIED  
0               1       03  
1               2       09  
2               2       21  
3               2        1  
4               2        1  
...           ...      ...  
523506          2        1  
523507          2        1  
523508          2        1  
523509          2        1  
523510          2        1  

[523511 rows x 9 columns]

In [9]:
#Removing unknown values
for x in df_model.columns:
    df_model = df_model[df_model[x]!=97]
    df_model = df_model[df_model[x]!=98]

In [10]:
df_model

AGE  INTUBED  DIABETES  ICU  CARDIOVASCULAR  ASTHMA  STATUS  \
1        55        1         1    2               2       2       0   
3        24        2         2    2               2       2       1   
4        30        2         2    2               2       2       1   
8        59        2         1    1               2       2       1   
16       45        2         2    2               2       2       1   
...     ...      ...       ...  ...             ...     ...     ...   
523481   26        2         2    2               2       2       1   
523484   64        2         1    2               2       2       1   
523486   50        2         1    2               2       2       1   
523495   65        2         1    2               2       2       1   
523507   51        2         2    2               2       2       1   

        PNEUMONIA DAY_DIED  
1               2       09  
3               2        1  
4               2        1  
8               1        1  
16              1        1  
...           ...      ...  
523481          1        1  
523484          2        1  
523486          1        1  
523495          2        1  
523507          2        1  

[117255 rows x 9 columns]

In [11]:
df_dummy = pd.get_dummies(df_model)

In [12]:
df_dummy

AGE  INTUBED  DIABETES  ICU  CARDIOVASCULAR  ASTHMA  STATUS  \
1        55        1         1    2               2       2       0   
3        24        2         2    2               2       2       1   
4        30        2         2    2               2       2       1   
8        59        2         1    1               2       2       1   
16       45        2         2    2               2       2       1   
...     ...      ...       ...  ...             ...     ...     ...   
523481   26        2         2    2               2       2       1   
523484   64        2         1    2               2       2       1   
523486   50        2         1    2               2       2       1   
523495   65        2         1    2               2       2       1   
523507   51        2         2    2               2       2       1   

        PNEUMONIA  DAY_DIED_1  DAY_DIED_01  ...  DAY_DIED_22  DAY_DIED_23  \
1               2       False        False  ...        False        False   
3               2        True        False  ...        False        False   
4               2        True        False  ...        False        False   
8               1        True        False  ...        False        False   
16              1        True        False  ...        False        False   
...           ...         ...          ...  ...          ...          ...   
523481          1        True        False  ...        False        False   
523484          2        True        False  ...        False        False   
523486          1        True        False  ...        False        False   
523495          2        True        False  ...        False        False   
523507          2        True        False  ...        False        False   

        DAY_DIED_24  DAY_DIED_25  DAY_DIED_26  DAY_DIED_27  DAY_DIED_28  \
1             False        False        False        False        False   
3             False        False        False        False        False   
4             False        False        False        False        False   
8             False        False        False        False        False   
16            False        False        False        False        False   
...             ...          ...          ...          ...          ...   
523481        False        False        False        False        False   
523484        False        False        False        False        False   
523486        False        False        False        False        False   
523495        False        False        False        False        False   
523507        False        False        False        False        False   

        DAY_DIED_29  DAY_DIED_30  DAY_DIED_31  
1             False        False        False  
3             False        False        False  
4             False        False        False  
8             False        False        False  
16            False        False        False  
...             ...          ...          ...  
523481        False        False        False  
523484        False        False        False  
523486        False        False        False  
523495        False        False        False  
523507        False        False        False  

[117255 rows x 40 columns]

In [13]:
from sklearn.model_selection import train_test_split as ttt
x = df_dummy.drop('AGE', axis = 1)
y = df_dummy.AGE.values
X_train,X_test,y_train,y_test = ttt(x,y ,test_size = 0.2, random_state = 42)


/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [14]:
X_train

INTUBED  DIABETES  ICU  CARDIOVASCULAR  ASTHMA  STATUS  PNEUMONIA  \
71996         2         2    2               2       1       1          1   
471960        2         2    2               2       2       1          1   
167341        2         2    2               2       2       1          2   
225442        1         2    2               2       2       0          1   
171762        2         2    2               2       2       0          1   
...         ...       ...  ...             ...     ...     ...        ...   
225521        1         2    2               2       2       0          1   
391688        2         1    1               2       2       1          2   
338135        2         2    2               2       2       1          1   
1050          2         2    2               2       2       0          1   
23793         1         1    2               2       2       0          2   

        DAY_DIED_1  DAY_DIED_01  DAY_DIED_02  ...  DAY_DIED_22  DAY_DIED_23  \
71996         True        False        False  ...        False        False   
471960        True        False        False  ...        False        False   
167341        True        False        False  ...        False        False   
225442       False        False         True  ...        False        False   
171762       False        False        False  ...        False        False   
...            ...          ...          ...  ...          ...          ...   
225521       False        False        False  ...        False        False   
391688        True        False        False  ...        False        False   
338135        True        False        False  ...        False        False   
1050         False        False        False  ...        False        False   
23793        False        False        False  ...        False        False   

        DAY_DIED_24  DAY_DIED_25  DAY_DIED_26  DAY_DIED_27  DAY_DIED_28  \
71996         False        False        False        False        False   
471960        False        False        False        False        False   
167341        False        False        False        False        False   
225442        False        False        False        False        False   
171762        False        False        False        False        False   
...             ...          ...          ...          ...          ...   
225521        False        False        False        False        False   
391688        False        False        False        False        False   
338135        False        False        False        False        False   
1050          False        False        False        False         True   
23793         False        False        False        False        False   

        DAY_DIED_29  DAY_DIED_30  DAY_DIED_31  
71996         False        False        False  
471960        False        False        False  
167341        False        False        False  
225442        False        False        False  
171762        False        False        False  
...             ...          ...          ...  
225521        False        False        False  
391688        False        False        False  
338135        False        False        False  
1050          False        False        False  
23793         False        False        False  

[93804 rows x 39 columns]

In [15]:
y_train

array([29, 35, 49, ...,  4, 76, 78])

MODEL BUILDING LINEAR REGRESSION

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
lr = LinearRegression()
scores = cross_val_score(lr,X_train,y_train, scoring = 'neg_mean_absolute_error')
scores
lr.fit(X_train,y_train)

LinearRegression()

In [17]:
np.mean(scores)

-13.691856968876573

In [18]:
from sklearn.linear_model import Lasso
lr_l = Lasso()
lr_l.fit(X_train,y_train)
scores = cross_val_score(lr_l,X_train,y_train, scoring = 'neg_mean_absolute_error')
scores

array([-13.88458887, -14.02084901, -13.95340107, -14.00145679,
       -13.89798726])

In [19]:
np.mean(scores)

-13.951656599186668

MODEL BUILDING LASO REGRESSION

In [20]:
from sklearn.ensemble import RandomForestRegressor
lf_r = RandomForestRegressor()
lf_r.fit(X_train,y_train)
scores = cross_val_score(lf_r,X_train,y_train, scoring = 'neg_mean_absolute_error')
scores

array([-13.47582564, -13.63352947, -13.50841032, -13.59330947,
       -13.49996293])

In [21]:
np.mean(scores)

-13.542207563764112

In [22]:
tpred_lr =lr.predict(X_test)
tpred_lr_l =lr_l.predict(X_test)
tpred_lf_r =lf_r.predict(X_test)


In [23]:
from sklearn.metrics import mean_absolute_error as mae
mae(y_test,tpred_lr)

13.648745106672724

In [24]:
mae(y_test,tpred_lr_l)

13.901358259249934

In [25]:
mae(y_test,tpred_lf_r)

13.524482479755552

PRODUCTION

In [26]:
#saving model using pickle
import pickle
pick1 = {'model': lf_r}
pickle.dump(pick1,open('model_f'+".p","wb"))

In [27]:
file_name = "model_f.p"
with open(file_name ,'rb')as pickled:
    data = pickle.load(pickled)
    model = data['model']
model.predict(X_test.iloc[1,:].values.reshape(1,-1))

/home/sendi/.local/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([64.3902166])

EMBEDDING CREATED MODEL IN DJANGO OR FLASK (API)

In [28]:
X_test

INTUBED  DIABETES  ICU  CARDIOVASCULAR  ASTHMA  STATUS  PNEUMONIA  \
206942        2         2    2               2       2       1          1   
21368         1         1    2               2       2       0          1   
150471        2         1    2               2       2       1          2   
218135        2         2    2               2       2       1          2   
417399        2         2    2               2       2       1          1   
...         ...       ...  ...             ...     ...     ...        ...   
236112        2         2    2               2       2       0          1   
338456        2         2    2               2       2       1          1   
25173        99         2   99               2       2       0          2   
172018        2         2    2               2       2       0          1   
231564        1         2    2               2       2       0          1   

        DAY_DIED_1  DAY_DIED_01  DAY_DIED_02  ...  DAY_DIED_22  DAY_DIED_23  \
206942        True        False        False  ...        False        False   
21368        False        False        False  ...        False        False   
150471        True        False        False  ...        False        False   
218135        True        False        False  ...        False        False   
417399        True        False        False  ...        False        False   
...            ...          ...          ...  ...          ...          ...   
236112       False        False        False  ...        False        False   
338456        True        False        False  ...        False        False   
25173        False        False        False  ...        False         True   
172018       False        False        False  ...        False        False   
231564       False        False        False  ...        False        False   

        DAY_DIED_24  DAY_DIED_25  DAY_DIED_26  DAY_DIED_27  DAY_DIED_28  \
206942        False        False        False        False        False   
21368         False        False        False        False        False   
150471        False        False        False        False        False   
218135        False        False        False        False        False   
417399        False        False        False        False        False   
...             ...          ...          ...          ...          ...   
236112        False        False         True        False        False   
338456        False        False        False        False        False   
25173         False        False        False        False        False   
172018         True        False        False        False        False   
231564        False        False        False        False        False   

        DAY_DIED_29  DAY_DIED_30  DAY_DIED_31  
206942        False        False        False  
21368         False        False        False  
150471        False        False        False  
218135        False        False        False  
417399        False        False        False  
...             ...          ...          ...  
236112        False        False        False  
338456        False        False        False  
25173         False        False        False  
172018        False        False        False  
231564        False         True        False  

[23451 rows x 39 columns]

In [29]:
#saving model using joblib
import joblib
joblib.dump(lf_r,'joblib_model')

['joblib_model']

In [30]:
model2 = joblib.load('joblib_model')

In [31]:
model2.predict(X_test.iloc[1,:].values.reshape(1,-1))

/home/sendi/.local/lib/python3.10/site-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([64.3902166])